objects/AnalysisInfo__c.object
<CustomObject>
    <description>The object that holds all data from the Field Analysis</description>
    <fields>
        <fullName>Date_Run__c</fullName>
        <label>Date Run</label>
        <type>Date</type>
    </fields>
    <label>AnalysisInfo</label>
    <nameField>
        <label>AnalysisInfo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AnalysisInfo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FieldInfo__c.object
<CustomObject>
    <description>Holds information about fields to be used in the ObjectInfo and AnalysisInfo</description>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Record__c</fullName>
        <label>Last Modified Record</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <label>Parent Object</label>
        <referenceTo>ObjectInfo__c</referenceTo>
        <relationshipLabel>FieldInfo</relationshipLabel>
        <relationshipName>FieldInfo</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Percent_Populated__c</fullName>
        <label>Percent Populated</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Populated_Number__c</fullName>
        <label>Populated Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FieldInfo</label>
    <nameField>
        <label>FieldInfo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FieldInfo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ObjectInfo__c.object
<CustomObject>
    <description>Holds info on an object for the AnalysisInfo object</description>
    <fields>
        <fullName>Number_of_Records__c</fullName>
        <label>Number of Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_AnalysisInfo__c</fullName>
        <label>Parent AnalysisInfo</label>
        <referenceTo>AnalysisInfo__c</referenceTo>
        <relationshipLabel>ObjectInfo</relationshipLabel>
        <relationshipName>ObjectInfo</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>ObjectInfo</label>
    <nameField>
        <label>ObjectInfo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectInfo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ResultsPageController.cls
/**************************************************************************
*    Created By:       Robert Jones
*    Date:             1 Aug 2017
*    Last Modified:    13 Aug 2017
*    Purpose:          This controller is used to retrieve the AnalysisInfo  
*                      ID from the URL, query for objects and related fields
*                      from the analysis, and creates a JSON string from the   
*                      query results to be passed to the VF page.
*
***************************************************************************/

public with sharing class ResultsPageController {

    public PageReference renderOutput() {
        return null;
    }


    //Custom settings used to pass information to the VF page.
    Public AnalysisInfo__c Analyze{get;set;}
    Public List<objectinfo__c> RObj{get;set;}
    Public String JSONstring {get;set;}
    Public Boolean shouldRenderOutput {get;set; }
    Public Date created;
    Public String createdStr{get;set;}
    Public User analyzeUser{get;set;}
    
    public ResultsPageController() {
    
        // Pulls the ID from the URL and queries for name of that AnalysisInfo Object
        analyze = [select name, Date_Run__c,createdbyid from analysisinfo__c where id = :apexpages.currentpage().getparameters().get('id')].get(0);
        analyzeUser = [select name from user where id = :analyze.createdbyid];
        shouldRenderOutput = False;
        created = date.newinstance(analyze.date_run__c.year(), analyze.date_run__c.month(), analyze.date_run__c.day());
        createdStr = String.valueOf(created);
        
        
        //Query used to get each object from AnalysisInfo along with the related fields and thier metadata for each object.
        RObj = (
        [Select id,name, Number_of_Records__c,
        (Select id, name, created_date__c, label__c, last_modified_date__c, percent_populated__c, populated_number__c, Last_Modified_Record__c from Fieldinfo__r) 
        from ObjectInfo__c where Parent_AnalysisInfo__c = :apexpages.currentpage().getparameters().get('id')]);
        
        //Creates a JSON string from the query results.
        JSONstring = JSON.serialize(RObj);
    }

    public PageReference goHome(){
        PageReference pageRef = new PageReference('/home/home.jsp');
        return pageRef;
    }

}